CREATE TABLE corp_info (
                              id bigint generated by default as identity,
                              corp_code varchar(255),
                              corp_name varchar(255),
                              modify_date varchar(255),
                              stock_code varchar(255),
                              primary key (id)
);

